* Scene pool for Town area
  - 1 Crier! A town crier draws near, bellowing the news! He
  bumps rudely into our heros in his vigourous shouting. (He is a pickpocket.
  Random party member makes a Challenging Scrutinize check to identiy this,
  or notice he has lost some gold a few scenes after the event.)

  - 2 A drunk stumbles by the party, and as they pass they notice he has
  slumped against an alley wall and seems to be sleeping... or dead. (50/50
  sleeping vs dead. Has a dagger, a cup, and a few coins)

  - 3 A party member finds a shiny silver sterling in the street!

  - 4 A party member sees a lowly brass penny lying disused in the gutter.
  
  - 5 The party hears shouting and commotion from within a nearby building.
  Then, after a tense moment, a man is roughly hurled from the front door and
  tumbles into the muck. The party stands in silent observation as he begins
  to dust himself off (the man, Christian, has been accused of cheating at
  cards. He curses a pox on his erstwhile friends and and stumbles drunkenly
  away.)

  - 6 A haggard old man grabs a party member and issues a cryptic warning:
  "going outside the walls, are you? beware the Mad Man of the Crake River!
  He'll crunch yer bones!"
