* White Peaks Campaign Overview
This is the first Zweihander campaign for both us (Joe and Greg) and our
players. As such, it is intended to provide a "tutorial" experience and run
the players over most of the major game systems.

** Setting: The White Peaks
The party begins their journey at the fortress of Bramhall, situated in the
rough and high mountain passes between the White Peaks. Bramhall is a
frontier fortress of the expansionist Kriegmarck, and is ordinally a
lightly-populated trader fort, built and owned by the respected Bram family.
However, a large horde of Skrellyng savages have recently passed near and at
currently occupying the lands surrounding Bramhall. Most of the farmers and
rural peoples have fled to the safety of the fortress, and the Count's
influence extends a very short distance beyond the walls.

** Act I: Delicate Dealings
The player party is approached by the Count, Morton Bram, as hired arms to
deal with a delicate situation: Bram's eldest son, Connor, is missing and has
been since the Skrellyng appearing nearly two weeks hence. The Count, of
course, maintains his own military operations, so a natural question arises
as to why he needs the help of five iterant vagabonds. The answer is that
the Count's hold on power is firm... but the issue of the succession is less
certain.

Succesion in a Marck is *elective*. This means all the landholders vote from
among the ruling family to select the next ruler of the Marck. Rival
neighboring duke Marck Otho and Morton's baron Saul Shadowmend (who is
secretly a witch) both have plausible competing claims to the title and if a
succession war is brewing, the will be the first to cause trouble.

Morton explains the player's mission: escape the siege, travel among the
Skrellyng, find his son, and bring him home. They will first need to pass the
guard at the castle walls and be let out the gates. As the player party is
not a part of Morton's regular forces, they will need special dispensation
for this. Morton hastily scrawls a note to this effect. Called away by other
concerns, Morton concludes that you should take some time to purchase
supplies and arms for your journey and then sally forth.

The players hopefully screw around in town trying to ready themselves for a
while (see `scenes/town_pool.org) before venturing to the gates. At the gates, they need to do
social intrigue to talk their way past a guard who doesn't accept Morton's
note (scenes/gate.org) or deal with him elseways (murder hobos). After
exiting the walls, the players draw from a plains encounter pool
(`scenes/plains_pool.org`) and prepare to act on their plan to find Connor.

** Act II: The Icemarsh
After neutralizing the Madman, the players may choose what do with him. If
they take him back to down, his father may congratulate you in the tavern,
and will pay you the prize he was offering (10g) and give you his favorite
dragon pistol along with 20 shot to keep you safe on your mission. The Madman
(Jake) will then join your party.

If the players do not bring the Madman back, he will still remember his old
memories and join the players. On the road back, they will encounter the two
Skrellyng dragging ??? and need to free him. Once they do this, ??? is in the
party and any captured Skrellyng will know that they were ordered to capture
an arcanist by Marshal van Graff. Unfortunately, they do not speak the common
tounge and will thus be worthless unless a translator can be found.

Further into the wilderness, the players may travel and encounter a number of
*wilderness encounters*. They must complete at least two before the final
encounter may even be rolled (van Graff at the farm house)Unfortunately, they
do not speak the common
tounge and will thus be worthless unless a translator can be found.

Further into the wilderness, the players may travel and encounter a number of
*wilderness encounters*. They must complete at least two before the final
encounter may even be rolled (van Graff at the farm house). They are listed
below, and full info is contained in the relevant scene files. After every
length of travel, roll 20% chance to have an encounter and if true, select
one from the following list.

*** 0 Caravan (caravan.org)
A caravan trundles down the road toward you, laden with goods and swaying in
the chill breeze. The merchants are in high spirits and ready to trade. They
also may have news.

*** 1 Refugees (refugees.org)
A group of what appear to be poor farmers approach to pass you on the road.
The whole family is traveling, and a pregnant woman and young child are
riding what is presumably the family's lone horse.

If asked, they will explain that a Skrellyng warband took up residence in a
nearby farmhouse and, fearing for their lives, they fled, knowing rape and
plunder were now only a young savage's whimsy away. The family is hungry, low
on food, and needs medicine for the children and wife. They ask if you can
spare any of these things, and if the player help them. 

*** 2 Bear
A bear appears in the distance. Roll awareness to notice it. If the bear
notices them, 80% that it is hungry and immediately aggressive. Otherwise it
will only attack when provoked. If they successfully feed or otherwise
befriend the bear, it will follow them and appear to help at the farmhouse
battle.

*** 3 Mercenaries (mercs.org)
You encounter a group of four men of war riding toward Bramhall. They are
tense but in good spirits, hungry to fight. They are riding to offer their
services to miltary leaders in the broiling conflict. If the
players want to recruit them, their fee is 15g weekly, plus half of any
liquid loot encountered. They would also be happy to buy extra ammo or
weapons, or sell the same in addition to possibly rendering the healer's
services.

(These are the same mercs the players will later encounter at the farmhouse
if not here)
*** 4 Slaughter (slaughter.org)
You feel a grim darkness before you see it: just over the crest of a hill,
you find what must be the remains of a merciless Skrellyng raid. The skulls
of men lie cloven asunder, beside their sodden corpses slumped over in the
mud. The stench of rotting human flesh strengthens as you approach.

Upon closer inspection, the travelers seem mostly likely to have been
merchants. Their cart lies disused, the draft horses nowhere to be found.
Perhaps they have been eaten by the savages. Several locked chests from the
merchants have been left mostly undisturbed, most likely too heavy to carry and
too tedious to sunder. (Arduous Coordination checks to unlock them)

The chests contain 50g and 60g each, as well as several items from the rich
pool.

*** 5 Bandits (bandits.org)
Bandits have set up an ambush for unware travelers. Make a Hard Awareness
check to spot it from a distance and a normal Awareness check to spot it just
before the trap springs. The bandits have no afiliation with anyone and are
little more than opportunistic peasants.

**** Bandits
***** Haakon
A long-faced bowman wearing a shabby sable jacket. Mostly likely stolen from
a dead nobleman. 

Com 41 5
Bra 38 4
Agi 37 3
Per 36 4
Fel 39 3
Wil 42 4

Damage 8
Peril 7

Cheap Shot

Awareness I
Martial Ranged I
Toughness I
Stealth I
Coordination I

fur armor, longbow, 20 arrows, dirk

***** Mek
A huge man with soulless eyes. You get the sense he has strangled many and
regretted none.

Com 41 5
Bra 38 4
Agi 37 3
Per 36 4
Fel 39 3
Wil 42 4

Damage 8
Peril 7

Hard to Kill

Awareness I
Simple Melee I
Toughness I
Stealth I
Coordination I

fur armor

***** Lorn
Lorn is unlike most other bandits; his fine face suggests a more privileged
upbringing than expected for a ruffian. His eyes gleam with malice.

Com 35 5
Bra 39 4
Agi 32 3
Per 40 4
Fel 39 3
Wil 42 4

Damage 8
Peril 7

Fencer's Panache

Awareness I
Martial Melee I
Toughness I
Intimidate I
Coordination I

fur armor, rapier, wooden shield

*** 6 van Graff at the Farmhouse (farmhouse.org)
The player party finally comes upon the occupied farmstead from which van
Graff is orchestrating the invasion. The Skrellyng activity is so numerous
the players will certainly notice them before being noticed themselves, and
have a choice in how to proceed.

There are obviously a very large number of Skrellyng present at this
location, more than 35 warriors in total. A frontal raid would be more than
suicidal. The players will need to think of a tactic to investigate this
situation without being savagely murdered or captured.

**** Mercenaries
***** Doern
A short bowman with a gruff complexion. He seems distrustful at all times.

Com 41 5
Bra 38 4
Agi 37 3
Per 36 4
Fel 39 3
Wil 42 4

Damage 9
Peril 7

Gruesome Shot

Awareness I
Martial Ranged I
Toughness I
Stealth I
Coordination I

mail armor, longbow, 20 arrows, dirk

***** Korum
A large and friendly-seeming man, built like a bear. His jovial nature belies
the violence beneath.

Com 41 5
Bra 38 4
Agi 37 3
Per 36 4
Fel 39 3
Wil 42 4

Damage 8
Peril 7

Hard to Kill

Awareness I
Simple Melee I
Toughness I
Stealth I
Coordination I

fur armor, garotte

***** Tekket
Tekket, the merciless woman. Years of disrespect and abuse have transformed
her into the machine of war crimes she is today. Fear her.

Com 40 6
Bra 38 4
Agi 40 6
Per 40 4
Fel 39 3
Wil 42 5

Damage 10
Peril 8

Apalling Mien
Clinch Fighter
Lightning Reaction
Gatecrasher

Awareness II
Martial Melee II
Martial Ranged II
Toughness II
Intimidate II
Coordination II

mail armor, pike, crossbow, 15 bolts

***** Kallo
A thin Skrellyng, with long hair. Very brave.

Com 37 3
Bra 38 4
Agi 31 4
Per 37 3
Fel 41 5
Wil 45 6

Damage 7
Peril 9

Simple Melee I
Toughness I
Stealth I
Coordination I

spear

***** Xommo
A thin Skrellyng, with long hair. Very brave.

Com 40 3
Bra 37 4
Agi 36 4
Per 37 3
Fel 41 5
Wil 45 6

Damage 7
Peril 9

Simple Melee I
Toughness I
Stealth I
Coordination I

spear

