* White Peaks Campaign Overview
This is the first Zweihander campaign for both us (Joe and Greg) and our
players. As such, it is intended to provide a "tutorial" experience and run
the players over most of the major game systems.

** Setting: The White Peaks
The party begins their journey at the fortress of Bramhall, situated in the
rough and high mountain passes between the White Peaks. Bramhall is a
frontier fortress of the expansionist Kriegmarck, and is ordinally a
lightly-populated trader fort, built and owned by the respected Bram family.
However, a large horde of Skrellyng savages have recently passed near and at
currently occupying the lands surrounding Bramhall. Most of the farmers and
rural peoples have fled to the safety of the fortress, and the Count's
influence extends a very short distance beyond the walls.

** Act I: Delicate Dealings
The player party is approached by the Count, Morton Bram, as hired arms to
deal with a delicate situation: Bram's eldest son, Connor, is missing and has
been since the Skrellyng appearing nearly two weeks hence. The Count, of
course, maintains his own military operations, so a natural question arises
as to why he needs the help of five iterant vagabonds. The answer is that
the Count's hold on power is firm... but the issue of the succession is less
certain.

Succesion in a Marck is *elective*. This means all the landholders vote from
among the ruling family to select the next ruler of the Marck. Rival
neighboring duke Marck Otho and Morton's baron Saul Shadowmend (who is
secretly a witch) both have plausible competing claims to the title and if a
succession war is brewing, the will be the first to cause trouble.

Morton explains the player's mission: escape the siege, travel among the
Skrellyng, find his son, and bring him home. They will first need to pass the
guard at the castle walls and be let out the gates. As the player party is
not a part of Morton's regular forces, they will need special dispensation
for this. Morton hastily scrawls a note to this effect. Called away by other
concerns, Morton concludes that you should take some time to purchase
supplies and arms for your journey and then sally forth.

The players hopefully screw around in town trying to ready themselves for a
while (see `scenes/town_pool.org) before venturing to the gates. At the gates, they need to do
social intrigue to talk their way past a guard who doesn't accept Morton's
note (scenes/gate.org) or deal with him elseways (murder hobos). After
exiting the walls, the players draw from a plains encounter pool
(`scenes/plains_pool.org`) and prepare to act on their plan to find Connor.

** Act II: The Icemarsh
After neutralizing the Madman, the players may choose what do with him. If
they take him back to down, his father may congratulate you in the tavern,
and will pay you the prize he was offering (10g) and give you his favorite
dragon pistol along with 20 shot to keep you safe on your mission. The Madman
(Jake) will then join your party.

If the players do not bring the Madman back, he will still remember his old
memories and join the players. On the road back, they will encounter the two
Skrellyng dragging ??? and need to free him. Once they do this, ??? is in the
party and any captured Skrellyng will know that they were ordered to capture
an arcanist by Marshal van Graff. Unfortunately, they do not speak the common
tounge and will thus be worthless unless a translator can be found.

Further into the wilderness, the players may travel and encounter a number of
*wilderness encounters*. They must complete at least two before the final
encounter may even be rolled (van Graff at the farm house)Unfortunately, they
do not speak the common
tounge and will thus be worthless unless a translator can be found.

Further into the wilderness, the players may travel and encounter a number of
*wilderness encounters*. They must complete at least two before the final
encounter may even be rolled (van Graff at the farm house). They are listed
below, and full info is contained in the relevant scene files. After every
length of travel, roll 20% chance to have an encounter and if true, select
one from the following list.

*** 0 Caravan (caravan.org)
A caravan trundles down the road toward you, laden with goods and swaying in
the chill breeze.

*** 1 Refugees (refugees.org)
A group of what appear to be poor farmers approach to pass you on the road.
The whole family is traveling, and a pregnant woman and young child are
riding what is presumably the family's lone horse.

If asked, they will explain that a Skrellyng warband took up residence in a
nearby farmhouse and, fearing for their lives, they fled, knowing rape and
plunder were now only a young savage's whimsy away. The family is hungry, low
on food, and needs medicine for the children and wife. They ask if you can
spare any of these things, and if the player help them. 

*** 2 Bear
A bear appears in the distance. Roll awareness to notice it. If the bear
notices them, 80% that it is hungry and immediately aggressive. Otherwise it
will only attack when provoked. If they successfully feed or otherwise
befriend the bear, it will follow them and appear to help at the farmhouse
battle.

*** 3 Mercenaries
You encounter a group of four men of war riding toward Bramhall. They are
tense but in good spirits, hungry to fight. They are riding to offer their
services to Lord Morton in his efforts to pacify the Skrellyng. If the
players want to recruit them, their fee is 15g weekly, plus half of any
liquid loot encountered. They would also be happy to buy extra ammo or
weapons, or sell the same in addition to possibly rendering the healer's
services.

*** 4 Slaughter
You feel a grim darkness before you see it: just over the crest of a hill,
you find what must be the remains of a merciless Skrellyng raid. The skulls
of men lie cloven asunder, beside their sodden corpses slumped over in the
mud. The stench of rotting human flesh strengthens as you approach.

Upon closer inspection, the travelers seem mostly likely to have been
merchants. Their cart lies disused, the draft horses nowhere to be found.
Perhaps they have been eaten by the savages. Several locked chests from the
merchants have been
