* White Peaks Campaign Overview
This is the first Zweihander campaign for both us (Joe and Greg) and our
players. As such, it is intended to provide a "tutorial" experience and run
the players over most of the major game systems.

** Setting: The White Peaks
The party begins their journey at the fortress of Bramhall, situated in the
rough and high mountain passes between the White Peaks. Bramhall is a
frontier fortress of the expansionist Kriegmarck, and is ordinally a
lightly-populated trader fort, built and owned by the respected Bram family.
However, a large horde of Skrellyng savages have recently passed near and at
currently occupying the lands surrounding Bramhall. Most of the farmers and
rural peoples have fled to the safety of the fortress, and the Count's
influence extends a very short distance beyond the walls.

** Act I: Delicate Dealings
The player party is approached by the Count, Morton Bram, as hired arms to
deal with a delicate situation: Bram's eldest son, Connor, is missing and has
been since the Skrellyng appearing nearly two weeks hence. The Count, of
course, maintains his own military operations, so a natural question arises
as to why he needs the help of five iterant vagabonds. The answer is that
the Count's hold on power is firm... but the issue of the succession is less
certain.

Succesion in a Marck is *elective*. This means all the landholders vote from
among the ruling family to select the next ruler of the Marck. Rival
neighboring duke Marck Otho and Morton's baron Saul Shadowmend (who is
secretly a witch) both have plausible competing claims to the title and if a
succession war is brewing, the will be the first to cause trouble.

Morton explains the player's mission: escape the siege, travel among the
Skrellyng, find his son, and bring him home. They will first need to pass the
guard at the castle walls and be let out the gates. As the player party is
not a part of Morton's regular forces, they will need special dispensation
for this. Morton hastily scrawls a note to this effect. Called away by other
concerns, Morton concludes that you should take some time to purchase
supplies and arms for your journey and then sally forth.

The players hopefully screw around in town trying to ready themselves for a
while (see `scenes/town_pool.org) before venturing to the gates. At the gates, they need to do
social intrigue to talk their way past a guard who doesn't accept Morton's
note (scenes/gate.org) or deal with him elseways (murder hobos). After
exiting the walls, the players draw from a plains encounter pool
(`scenes/plains_pool.org`) and prepare to act on their plan to find Connor.

** Act II: The Icemarsh
After neutralizing the Madman, the players may choose what do with him. If
they take him back to down, his father may congratulate you in the tavern,
and will pay you the prize he was offering (10g) and give you his favorite
dragon pistol along with 20 shot to keep you safe on your mission. The Madman
(Jake) will then join your party.

If the players do not bring the Madman back, he will still remember his old
memories and join the players. On the road back, they will encounter the two
Skrellyng dragging ??? and need to free him. Once they do this, ??? is in the
party and any captured Skrellyng will know that they were ordered to capture
an arcanist by Marshal van Graff. 
